version: 2.1

commands:
  install_dependencies:
    description: "Install dependencies"
    steps:
      - run: yarn install
executors:
  default:
    docker:
      - image: cimg/node:<<parameters.to>>
    working_directory: ~/project
    parameters:
      to:
        type: "string"
        default: "14.17"

jobs:
  build:
    executor: default
    steps:
      - checkout
      - install_dependencies
      - run: |
          - yarn intall serve
          - npm run build

workflows:
  build:
    jobs:
      - build
