version: 2.1

commands:
  install_dependencies:
    description: "Install dependencies"
    steps:
      - run: yarn install
executors:
  default:
    docker:
      - image: cimg/node:<<parameters.to>>
    working_directory: ~/project
    parameters:
      to:
        type: "string"
        default: "lts"


jobs:
  build:
    docker:
      - image: cimg/node:<<parameters.to>>
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Build application
          command: |
            mkdir -p output
            cat "Compiled code" > output/test.txt
      - persist_to_workspace:
          root: output
          paths:
            - test.txt
    parameters:
      to:
        type: "string"
        default: "lts"
  test:
    docker:
      - image: cimg/node:<<parameters.to>>
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Run tests
          command: |
            echo "Running tests..."
            pwd
            cat /workspace/test.txt
    parameters:
      to:
        type: "string"
        default: "lts"

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build