version: 2.1

jobs:
  build:
    working_directory: ~/project/portfolio
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            ls -al
            pwd
            cd /home/circleci/project/portfolio
            ls

   
  test:
    working_directory: ~/project/portfolio
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - run:
          name: The Second Step
          command: npm run test

workflows:
  build_test:
    jobs:
      - build
      - test:
            requires:
              - build 



