version: 2.1

executors:
  my-executor:
    parameters:
      version:
        type: string
        default: "14.17"
    docker:
      - image: cimg/node:<< parameters.version >>

jobs:
  build:
    executor: my-executor
    steps:
      - run: echo "Hello executor!"
   
  test:
    executor: my-executor
    steps:
      - run: echo "Hello executor!"

workflows:
  build_test:
    jobs:
      - build
      - test:
            requires:
              - build 



