version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            yarn install
      - run:
          name: Build application
          command: |
            mkdir -p output
            echo "Compiled code" > output/test.txt
      - persist_to_workspace:
          root: .
          paths:
            - output

  test:
    docker:
      - image: cimg/node:14.17
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run tests
          command: |
            echo "Running tests..."
            pwd
            ls -la
            cd ..
            ls -la

workflows:
  version: 2
  build:
   jobs:
    - build
    - test:
        requires:
          - build
