version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:14.17
    steps:
     - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'

   

workflows:
  prac_build:
    jobs:
      - build



