version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Build application
          command: |
            mkdir -p output
            echo "Compiled code" > output/application.zip
      - persist_to_workspace:
          root: output
          paths:
            - application.zip

  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Run tests
          command: |
            echo "Running tests..."
            pwd
            cat /workspace/application.zip

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
