version: 2.1

jobs:
  build:
    working_directory: ~/project/portfolio
    docker:
      - image: cimg/node:14.17
    steps:
     - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            ls -al
            pwd
            cd ~/project/portfolio
            ls -al

   

workflows:
  prac_build:
    jobs:
      - build



